version: "2.3"
services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_ALLOW_EMPTY_ROOT_PASSWORD: 'yes'
    ports:
      - "13306:3306"
    volumes:
      - "/Projects/IdeaProjects/ElevatorDriver/mysql_data:/var/lib/mysql"

  srv-config:
    image: edu2021/srv-config:latest
    container_name: srv-config
    environment:
      - APP_ENV=dev
    ports:
      - "16002:6002"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:6002/actuator/health" ]
      timeout: 10s
      retries: 3
    depends_on:
      mariadb:
        condition: service_started

  api-admin:
    image: edu2021/api-admin:latest
    container_name: api-admin
    environment:
      - APP_ENV=dev
      - config.server.path=http://srv-config:6002
    ports:
      - "16060:6060"
    depends_on:
      srv-config:
        condition: service_healthy