version: "2.3"
services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=qa123Z45
      - MYSQL_ALLOW_EMPTY_PASSWORD=Y
      - MYSQL_RANDOM_ROOT_PASSWORD=N
#      - MYSQL_ROOT_HOST='%'
    ports:
      - "13306:3306"

  srv-config:
    image: edu2021/srv-config
    container_name: srv-config
    environment:
      - APP_ENV=dev
    ports:
      - "16002:6002"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:6002/actuator/health" ]
      timeout: 10s
      retries: 3
    depends_on:
      mysql:
        condition: service_started

  api-admin:
    image: edu2021/api-admin:latest
    container_name: api-admin
    environment:
      - APP_ENV=dev
      - config.server.path=http://srv-config:6002
    ports:
      - "16060:6060"
    depends_on:
      srv-config:
        condition: service_healthy