server:
  port: 6050
spring:
  datasource:
    url: jdbc:mysql://mariadb:3306/api_engine?enabledTLSProtocols=TLSv1.2&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: admin123